export enum Events {
  /** 房间相关（广播） */
  ROOM_EXILE = "ROOM_EXILE",
  ROOM_JOIN = "ROOM_JOIN",
  GAME_BEGIN = "GAME_BEGIN",
  GAME_END = "GAME_END",

  /** 游戏相关（广播） */
  CHANGE_STATUS = "CHANGE_STATUS",
  NOTICE_GET_STATUS = "NOTICE_GET_STATUS",
  SHOW_MSG = "SHOW_MSG",

  /** 请求-响应类（ack callback 模式） */
  AUTH = "AUTH",
  ROOM_CREATE = "ROOM_CREATE",
  ROOM_JOIN_REQ = "ROOM_JOIN_REQ",
  ROOM_INIT = "ROOM_INIT",
  GAME_BEGIN_REQ = "GAME_BEGIN_REQ",
  GAME_STATUS = "GAME_STATUS",
  GAME_ACT = "GAME_ACT",
  HINT_WOLF_KILL = "HINT_WOLF_KILL",
  HINT_GET_WOLFS = "HINT_GET_WOLFS",
  HINT_WITCH_GET_DIE = "HINT_WITCH_GET_DIE",
}